### ISSUE TITLE
Move installation packages default directory to the quipucords directory and allow overriding default

### ISSUE THREAD

**Issue by kholdaway** [quipucords/qpc-tools#7]
Allow offline packages directory to be specified via the installer AND default it to a better location.  Converting this to an RPM made this a little more difficult to locate.  See current directions below.

## Old package location
```
1. Create a ``packages`` directory to use to install the downloaded packages by entering the following command::

    # mkdir -p /usr/{lib}/qpc-tools-{x.y.z}/install/packages

- ``{lib}`` is your library version either lib or lib64
- ``{x.y.z}`` is the version of the qpc-tools rpm
```

-----

### Quipucords Home Directory
1.  They can set the root `quipucords` home directory via a variable.  The persistent files and packages will live there.  The directory structure is shown below.  The ansible playbook will expect all offline files to be in the directory structure below.
```
- quipucords
    - server
        - volumes
            - logs
            - ssh
            - data
        - packages
    - cli
        - packages
```
### Quipucords Offline Scenario
A customer who wishes to install offline must create a directory anywhere on their file system with the offline rpms and constainer images.  They will pass the install function the `--offline-install-path` path to point to the directory with all offline binaries.  The python code is responsible to move the offline files to the appropriate `quipucords home` directory.

The online install needs to go to `server/packages` & `cli/packages` when pulling from github.

The offline will now be passed in through the `qpc-tools` cli, and then moved to the `server/packages` & `cli/packages`

**Comment by myersCody** [comment]
~I was thinking about his earlier, and I think the fix may be to change it here:~
~https://github.com/quipucords/qpc-tools/blob/master/install/roles/init/tasks/init_vars.yml#L23~

~From `ansible_env['PWD']` to `ansible_env['HOME']` like we do here: https://github.com/quipucords/qpc-tools/blob/master/install/qpc_playbook.yml#L18~

~Then the default will be `~/packages`~

**New & better design now in the description.**

**Comment by myersCody** [comment]
Parts to close this issue: 
- [ ] **Section A**: Update the install roles to go to `server/packages` & `cli/packages` as well as clean up the man page. 
- [ ] **Section B**: Fix the `qpc-tools` cli for the offline install.

**Comment by myersCody** [comment]
https://github.com/quipucords/qpc-tools/pull/18
