### ISSUE TITLE
Cut 0.2.3 qpc-tools release

### ISSUE THREAD

**Issue by kholdaway** [quipucords/qpc-tools#83]
Cut 0.2.3 qpc-tools release

**Comment by myersCody** [comment]
# Features
- [Issue 2](https://github.com/quipucords/qpc-tools/issues/2) - Add support for CentOS 8
- [PR 78](https://github.com/quipucords/qpc-tools/pull/78) - Bump release version to 0.2.3
# Bugs
- [Issue 80](https://github.com/quipucords/qpc-tools/issues/80) - Fix bad Ansible condition that was handled by downstream patch
