### ISSUE TITLE
Test qpc-tools 0.2.3, qpc cli 0.9.3, and quipucords server 0.9.2 pre-releases

### ISSUE THREAD

**Issue by kholdaway** [quipucords/qpc-tools#85]
# Online new install (ash)
Run each test on RHEL 6/7/8 and CentOS 6/7/8.
- [x] yum install the qpc-tools CLI (0.2.3)
- [x] Online latest cli release (0.9.3)
- [x] Online latest server release (0.9.2)
- [x] Run a vcenter scan
- [x] Run a network scan
- [x] Run a satellite scan
- [x] Load the UI
- [x] View the documentation that is embedded in the UI
- [x] View the manpage for the qpc-tools CLI
- [x] View the manpage for the qpc CLI

# Online upgrade install (cody)
- [x] yum install the qpc-tools CLI (0.2.2)
- [x] Online latest cli release (0.9.2)
- [x] Online latest server release (0.9.1)
- [x] Run a vcenter scan
- [x] yum install the qpc-tools CLI (0.2.3)
- [x] Online latest cli release (0.9.3)
- [x] Online latest server release (0.9.2)
- [x] Load the UI and view scans
- [x] View the documentation that is embedded in the UI
- [x] View the manpage for the qpc-tools CLI
- [x] View the manpage for the qpc CLI
- [x] Run a vcenter scan

# Offline new install (Kevan)
Run each test on RHEL 6/7/8 and CentOS 6/7/8.
- [x] yum install the qpc-tools CLI (0.2.3) without connectivity
- [x] Latest cli release (0.9.3) without connectivity
- [x] Latest server release (0.9.2) without connectivity
- [x] Run a vcenter scan
- [x] Run a network scan
- [x] Run a satellite scan
- [x] Load the UI
- [x] View the documentation that is embedded in the UI
- [x] View the manpage for the qpc-tools CLI
- [x] View the manpage for the qpc CLI

# Offline upgrade install (ash)
- [x] yum install the qpc-tools CLI (0.2.2) without connectivity
- [x] Latest cli release (0.9.2) without connectivity
- [x] Latest server release (0.9.1) without connectivity
- [x] Run a vcenter scan
- [x] yum install the qpc-tools CLI (0.2.3) without connectivity
- [x] Latest cli release (0.9.3) without connectivity
- [x] Latest server release (0.9.2) without connectivity
- [x] Load the UI and view scans
- [x] View the documentation that is embedded in the UI
- [x] View the manpage for the qpc-tools CLI
- [x] View the manpage for the qpc CLI
- [x] Run a vcenter scan

**Comment by myersCody** [comment]
We have finished testing the prereleases.
